name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Setup Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.8'

      - name: Run tests
        run: swift test --enable-code-coverage --parallel
