name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Setup Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.8'

      - name: Run tests
        run: swift test --enable-code-coverage --parallel
